projectPath: "."
documents:
  - description: "Project structure overview"
    outputPath: project-structure.md
    sources:
      - type: tree
        sourcePaths:
          - src
          - migrations
          - templates
        filePattern: "*.php,*.twig"
        excludePaths:
          - vendor
          - node_modules
          - .git
      - type: file
        sourcePaths:
          - src
          - migrations
          - templates
        filePattern: "*.php,*.twig"
        excludePaths:
          - vendor
          - node_modules
          - .git